sudo: required

services:
  - docker

before_install:
  - docker build -t feries/php7.1 .
  - docker run --name php7.1 -d feries/php7.1

script:
  - docker exec php7.1 php -v
  - docker exec php7.1 sh -c "php -v | grep OPcache"
  - docker exec php7.1 sh -c "php -v | grep Xdebug"
  - docker exec php7.1 composer --version
  - docker exec php7.1 sh -c "php -i | grep intl"
  - docker exec php7.1 sh -c "php -i | grep 'API Extensions => pdo_mysql'"